### ISSUE TITLE
Feature: support NodePath dynamic imports

### ISSUE THREAD

**Issue by ntucker** [Anber/wyw-in-js#30]
## Environment

- wyw-in-js version: 0.2.2
- custom processor:
- Bundler (+ version): webpack@5.89.0
- Node.js version: 20.10.0
- OS: Ubuntu on WSL

## Description

`Error: /temp/storybook-stories.js: Dynamic import argument must be a string or a template literal`

<details collapsed><summary><b>Full error</b></summary>

```bash
ERROR in ./storybook-stories.js
Module build failed (from ./node_modules/@wyw-in-js/webpack-loader/lib/index.js):
Error: /home/ntucker/src/temp/storybook-stories.js: Dynamic import argument must be a string or a template literal
    at PluginPass.CallExpression (/home/ntucker/src/temp/node_modules/@wyw-in-js/transform/lib/plugins/dynamic-import.js:28:17)
    at newFn (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/visitors.js:160:14)
    at NodePath._call (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/home/ntucker/src/temp/node_modules/@babel/traverse/lib/index.js:52:34)
    at transformFile (/home/ntucker/src/temp/node_modules/@babel/core/lib/transformation/index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (/home/ntucker/src/temp/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at /home/ntucker/src/temp/node_modules/@babel/core/lib/transform-ast.js:23:33
```

</details>

When using storybook it creates a virtual file that includes a dynamic import. This breaks the build.

Problem is [here](https://github.com/Anber/wyw-in-js/blob/main/packages/transform/src/plugins/dynamic-import.ts#L36)

Context on [nodepath](https://www.tabnine.com/code/javascript/classes/babel__traverse/NodePath)

## Reproducible Demo

https://github.com/ntucker/wyw-in-js-storybook

```bash
git clone https://github.com/ntucker/wyw-in-js-storybook
cd wyw-in-js-storybook
yarn storybook
```

**Comment by layershifter** [comment]
I tried clone the repo, install deps and did `yarn storybook`:

<img width="766" alt="image" src="https://github.com/Anber/wyw-in-js/assets/14183168/77d9c618-a1df-4d4b-9500-90b27730cae4">

(node 20)

@ntucker can you please provide more details? It seems that something is missing in the repro.

**Comment by Pfeifenjoy** [comment]
I have the same issue but use vite with wyw. For me it fails if I use react-router-dom since this library has a dynamic import with a non string value.

I tried to ignore that package but somehow in storybook it always applies wyw on all node_modules. Interestingly if I simply build my project I do not see the error.
